import fs from "fs";
import path from "path";

export function generateEnvExample(schema, filePath = ".env.example") {
  let content = "# Auto-generated by ENV Guard\n\n";

  for (const key in schema) {
    const rule = schema[key];
    const description = rule.description ? `# ${rule.description}\n` : "";
    const defaultVal = rule.default !== undefined ? rule.default : "";
    content += `${description}${key}=${defaultVal}\n\n`;
  }

  const outPath = path.resolve(process.cwd(), filePath);
  fs.writeFileSync(outPath, content.trim() + "\n", "utf-8");

  console.log(`✅ ${filePath} generated successfully!`);
}
